#!/bin/sh

name="wifi_config"

start() {
  ip link set wlan0 up
  wpa_passphrase "Swift Navigation Ruckus" centimeter > your_SSID.conf
  wpa_supplicant -B -i wlan0 -c your_SSID.conf
  dhcpcd wlan0
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh

